version: '3'
services:

  app:
    build: ./docker/app
    container_name: laravel_app
    ports:
     - "80:80"
    volumes:
     - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
      TZ: 'Asia/Tokyo'
    tty: true
    command: /bin/bash
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf